###

POST http://localhost:2277/api/v1/hello
Content-Type: application/json
Access-Token: lnwza007@rushmi0.win

{
  "message": "test"
}

###

POST https://demo.rushmi0.win/api/v1/hello
Content-Type: application/json
Access-Token: lnwza007@rushmi0.win

{
  "message": "test"
}