###

POST https://demo.rushmi0.win/api/v1/debit/create
Content-Type: application/json

{
  "full_name": "Watcharapol Phongwilai",
  "createdAt": "28/10/2024",
  "content": {
    "nick_name": "lnwza007",
    "email": "ph.watcharapol_st@tni.ac.th"
  }
}

### Watcharapol Phongwilai

GET https://demo.rushmi0.win/api/v1/user-info/Watcharapol%20Phongwilai
Content-Type: application/json

###

GET https://demo.rushmi0.win/api/v1/debit-balance?fullName=Watcharapol%20Phongwilai
Content-Type: application/json

###

GET https://demo.rushmi0.win/api/v1/debit/deposits/Watcharapol%20Phongwilai
Content-Type: application/json

###




